implement phone number verification with SMS
swent-group4/sudden-bump pull request #118
Opened 2024-10-31 23:35 UTC by marinovdeyan

- SignUp view, UserViewModel and UserRespository updated to implement the phone verification of Firestore
- SMS sending currently not functional because we have no payment method in Firestore, but you can use the "testing phone numbers" feature
- no tests implemented yet, but feature seems functional with manual end-to-end test

@Sobell13 could you please have a look at what I've done so far and confirm to me that everything is in accordance with your implementation of UserViewModel and UserRepository(Firestore)?

I will not be merging this PR because it is currently untested (well, it works when I interact with it, but there are no unit and UI tests) and will definitely require polishing up, but I need some confirmation that my implementation fits with our current structure.

2024-11-07 23:47 UTC, marinovdeyan commented
Tests have now been added to cover all the development in SignUp.kt (View), UserViewModel.kt and UserRepositoryFirestore (Model) for the sending and verifying of SMS codes.

What remains to be tested is actually sending real SMS on a real Android device (which I don't have - the sending of real SMSs is disabled on the emulator).

2024-11-10 14:23 UTC, DanR2003 approved these changes
The implementation of phone verification with Firestore looks well made:

- The work on SignUp view, UserViewModel, and UserRepository is well integrated and is thoughtfully implemented, even tough documentation is not very present.

- For the future, I think it would be a good idea to create separate viewModel files as the UserViewModel is becoming increasingly large and hard to read.

- It's nice to see that Firestore’s "testing phone numbers" feature was used as a workaround for SMS functionality, given the limitations. 

- SignUp.kt, UserViewModel.kt, and UserRepositoryFirestore look carefully tested.

 I think this PR is safe to merge into the main branch even tough SMS verification wasn't tested yet on an actual device, because the files have undergone carefull testing. 
 Tip for the future: Check that 2 users can't have the same phone number (it should be unique). At the moment we just check that the email is unique.

2024-11-11 14:39 UTC, DanR2003 commented on app/.attach_pid5305
Should this empty file exist?

2024-11-11 14:42 UTC, DanR2003 approved these changes

2024-11-11 16:58 UTC, ifaresse requested changes
When an user try to register using a non test phone number you get this error : 
![Capture d'écran 2024-11-11 174217](https://github.com/user-attachments/assets/9a03dcaa-f363-4580-9cb4-d0c49af35772)
Otherwise the interface works well :
![photo_2024-11-11_17-47-57 (2)](https://github.com/user-attachments/assets/49be7c18-b2bb-4c91-963b-af4fac493f65)
![photo_2024-11-11_17-47-57](https://github.com/user-attachments/assets/6144ab26-1b4d-43be-8ab9-81e3a914566b)
One good thing would be to have a limit of 6 characters in the verification code.

2024-11-11 17:00 UTC, marinovdeyan commented on app/.attach_pid5305
No, it's something that just appeared there without my knowledge. I will delete it.

2024-11-11 17:17 UTC, marinovdeyan commented on app/.attach_pid5305
I have removed this in my latest push to this PR. Case closed.

2024-11-11 17:41 UTC, ifaresse approved these changes
LGTM

2024-11-11 17:57 UTC, merged