feat(messages): now displays the list of current discussions with the…
swent-group4/sudden-bump pull request #207
Opened 2024-11-20 13:41 UTC by Sobell13

… user's friends

Changed the chat summary feature in order to correctly display in a time descending order the friends an user has a conversation with, with a preview of the latest message

2024-11-22 23:41 UTC, ifaresse requested changes
Look at my comment for the commented test and otherwise the app crashed when I navigate to the list of current discussions.
![Capture d'écran 2024-11-23 003530](https://github.com/user-attachments/assets/3b19a427-2f94-4035-9ae4-53edf84be3cc)
It displays this error in the log.

2024-11-22 23:41 UTC, ifaresse commented on app/src/test/java/com/swent/suddenbump/model/chat/ChatSummaryTest.kt
Why the test dateWorksWithNonNullDate() is commented ? Still useful or can be deleted ?

2024-11-23 10:36 UTC, Sobell13 commented on app/src/test/java/com/swent/suddenbump/model/chat/ChatSummaryTest.kt
The test is not useful anymore

2024-11-23 10:37 UTC, Sobell13 commented
The messages with the previous version of the app did not have the same format as the newest one, making it crash when retrieving old messages.
In order to change that, deleting messages and sending only with the latest version is mandatory.

2024-11-23 10:54 UTC, ifaresse commented on app/src/test/java/com/swent/suddenbump/model/chat/ChatSummaryTest.kt
Can you remove it then ?

2024-11-23 22:26 UTC, ifaresse approved these changes
LGTM !

2024-11-23 22:26 UTC, ifaresse commented on output_diff.txt
what is this file ?

2024-11-23 22:27 UTC, Sobell13 commented on app/src/test/java/com/swent/suddenbump/model/chat/ChatSummaryTest.kt
It's deleted now with the latest commit

2024-11-23 22:30 UTC, Sobell13 commented on output_diff.txt
I forgot to delete it.
Should be good now.

2024-11-23 23:48 UTC, merged