228 - fixing profile pictures
swent-group4/sudden-bump pull request #229
Opened 2024-11-26 15:43 UTC by Sobell13

The app needed several fixes, made in this Pull Request, such as :

1. Changing its profile picture
    The Settings Screen now uploads in the Firebase database the newest photo the user wants, as well as updating its value locally.
2. Downloading friends' profile pictures
    Retrieving a user's friends offer the feature of downloading the corresponding profile picture (if present).
3. Displaying friends' profile pictures
    The profile pictures are now displayed next to the friend's information (if present) in the Overview, Messages and ContactPage screen.

2024-11-28 16:08 UTC, ifaresse requested changes
The profile pictures brings latency to the app, try to change it if you can.

2024-11-28 16:08 UTC, ifaresse commented on app/src/main/java/com/swent/suddenbump/ui/overview/Overview.kt
Maybe we need to scale down the profil pictures because right now the overview screen is very laggy.

2024-11-29 15:20 UTC, ifaresse approved these changes
LGTM, it still has latency but this will be tackled next sprint.

2024-11-29 15:21 UTC, DanR2003 approved these changes
- The changes done in this PR work properly: I can change the profile picture in the Settings as well as see my friends' profile photos. 
- The testing looks very extensive and carefully made which is very positive
- It's true that there is a bit of lag, but it is not very bad and the app is still usable

For me, this PR is good to be merged, just please eliminate the lag as soon as you can :)

2024-11-29 15:21 UTC, DanR2003 commented on app/src/androidTest/java/com/swent/suddenbump/ui/overview/SettingsScreenTest.kt
> +
Good job with the tests! They cover a lot of cases and seem very extensive.

2024-11-29 15:21 UTC, DanR2003 commented on app/src/test/java/com/swent/suddenbump/model/user/UserRepositoryFirestoreTest.kt
> +
Amazing job with this test! The mocking must have been quite challenging but I see you handled this quite well :)

2024-11-29 15:24 UTC, merged