Unsend friend request
swent-group4/sudden-bump pull request #310
Opened 2024-12-18 17:17 UTC by daliaghosn

2024-12-18 21:51 UTC, ifaresse requested changes
Please remove the unnecessary comment, then it should be good !

2024-12-18 21:51 UTC, ifaresse commented on app/src/androidTest/java/com/swent/suddenbump/ui/contacts/ContactTest.kt
> +    // you might need to wait for the recomposition or flow update.
Maybe delete this comment

2024-12-19 11:25 UTC, ifaresse approved these changes
LGTM !

2024-12-19 11:27 UTC, merged

2024-12-19 11:28 UTC, daliaghosn commented on app/src/androidTest/java/com/swent/suddenbump/ui/contacts/ContactTest.kt
> +    // you might need to wait for the recomposition or flow update.
Thanks, it's done.